replicaCount: 1

nameSpace: default 

image:
  repository: azureregistry.azurecr.cn/zxspider/testgetcaiwuinfo
  pullPolicy: IfNotPresent
  tag: "10"

imagePullSecrets:
- name: harborsecret 

nameOverride: ""

fullnameOverride: ""


podAnnotations: {}

securityContext:
  privileged: true

service:
  type: ClusterIP
  port: 20001
  targetPort: 20001 

command:
  enabled: true 
  value: '/home/developer/project9/GetCaiWuInfo/shell/add_new_spider.sh > add_new_spider.txt &> /dev/null'

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

configSet:
  settingfile: settings.py
  setfile:  set.py

volume:
  enabled: true
  settingPath: "/home/developer/project9/GetCaiWuInfo/GetCaiWuInfo/settings.py"
  name: config-spider-getcaiwuinfo
  setPath: "/home/developer/project9/GetCaiWuInfo/GetCaiWuInfo/set.py"
  nfsip: "192.168.2.6"

crontablog:
  enabled: true
  path: "/data/log/spi/GetCaiWuInfo/crontablog"  
  name: crontablog
  mountPath: "/home/developer/project9/crontablog/"
log:
  enabled: true
  path: "/data/log/spi/GetCaiWuInfo/log"
  name: log
  mountPath: "/home/developer/project9/GetCaiWuInfo/log/"
jiacrontabdata:
  enabled: true
  path: "/data/log/spi/GetCaiWuInfo/jiacroantabdata"
  name: jiacrontabdata
  mountPath: "/opt/jiacrontabd/data"

configmap:
  enabled: true
  name: spider-getcaiwuinfo-config     

